import Header from '../../components/header'
import Head from 'next/head'

export default function brandsPage() {
    return (
        <>
            <Head>
                <title>Brands</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/favicon.ico" />
            </Head>
            <Header></Header>
        </>
    )
}