import Header from '../../components/header'
import Head from 'next/head'


export default function creatorsPage() {
    return (
        <>
            <Head>
                <title>Creators</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/favicon.ico" />
            </Head>
            <Header></Header>

            

        </>
    )
}