import Header from '../../components/header'
import Head from 'next/head'
import Eventcards from '../../components/eventCards'
import eventsStyles from '../../styles/eventsPage.module.css'




export default function eventsPage() {
    return (
        <>
            <Head>
                <title>Events</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/favicon.ico" />
            </Head>
            <Header></Header>
            <div className={eventsStyles.container}>
                <div className={eventsStyles.cardDeck}>
                    <Eventcards></Eventcards>
                </div>
            </div>
        </>
    )
}