import Header from '../../components/header'
import Head from 'next/head'
import Image from 'next/image'
import recipesStyles from '../../styles/recipesPage.module.css'
import React from 'react';
import { render } from 'react-dom';

class RecipesPage extends React.Component {
    constructor(props) {
        super(props);
        this.handleClick = this.handleClick.bind(this);
        this.state = {showModal: false};
    }
    handleClick() {
        this.setState({showModal: true});
        console.log("click")
    }    

    render() {
        const showModal = this.state.showModal;
        return (
            <>
                <Head>
                    <title>Recipes</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/public/images/favicon.ico" />
                </Head>
                <Header></Header>
                <div className={recipesStyles.container}>
                    <div className={recipesStyles.modalContainer}>
                    {showModal &&
                        <img 
                            className={recipesStyles.img}
                            src="/images/recipe.jpg"
                            height={341}
                            width={500}
                        >
                        </img>
                    }            

                    </div>

                    <div className={recipesStyles.cardDeck}>
                        <div className={recipesStyles.card}>
                            <div className={recipesStyles.recipeImageContainer}>
                                <Image
                                    src='/images/green.jpg'
                                    height={170}
                                    width={250}
                                >
                                </Image>
                            </div>
                            <div className={recipesStyles.textContainer}>
                                <h1 className={recipesStyles.h1}>Thai for Two <br></br>Organic Green Curry</h1>
                                <button className={recipesStyles.button} onClick={this.handleClick}>View Recipe</button>
                            </div>
                        </div>
                    </div>
                </div>
            </>
        )
    }    
}

export default RecipesPage;