import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from '../components/nav'

export default function Home() {
  return (
    <>
      <Head>
        <title>Grapevine Village</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>


      <div className={styles.topBar}>
        <div className={styles.topBarCentered}>
          <h2 className={styles.h2}>40% SALE ON SELECT FEATURED FOOD ITEMS*</h2>
        </div>  
      </div>

      <header className={styles.header}>
        <Nav></Nav>
      </header>
      
      <div className={styles.container}>


        <div className={styles.heroText}>
          <div className={styles.heroHeading}>
            <h1>MEET MINGSBINGS <br></br>CHEF MING TSAI</h1>
          </div>
          <div className={styles.heroBody}>
            <p>Ming Tsai is a chef, restauranteur, cookbook author, James Beard award winner, Emmy Award winner, and host of the longest-running cooking show on PBS, now in its 17th season. </p>
            <p>As a culinary and cultural pioneer of East meets West cuisine, he’s led the way for a creative, thoughtful, and delicious blending of flavors, temperatures, and textures while trailblazing a path for generations.
            </p>
          </div>   
        </div>
        <div className={styles.heroImage}>
          <Image
            src="/images/veggies.png"
            height={542}
            width= {668}
          ></Image>
        </div>

        <div className={styles.cardDeck}>
          <div className={styles.cardOne}>
            <div className={styles.textContainer}>
              <p>EVENTS | MAY 05 2021</p>
              <h1 className={styles.h1}>LEARN BASIC BING PREP</h1>
              <button className={styles.button}>REGISTER</button>
            </div>
            <div className={styles.picContainer}>
            <Image
              className={styles.logoPic}
              src="/images/mingslogo.svg"
              height={180}
              width={126}
            ></Image>
            </div>  
          </div>
          <div className={styles.cardOne}>
            <div className={styles.textContainer}>
              <p>EVENTS | MAY 05 2021</p>
              <h1 className={styles.h1}>LEARN BASIC BING PREP</h1>
              <button className={styles.button}>REGISTER</button>
            </div>
            <div className={styles.picContainerTwo}>
            <Image
              className={styles.chefPic}
              src="/images/chef.png"
              height={180}
              width={170}
            ></Image>
            </div>  
          </div>
          <div className={styles.cardOne}>
            <div className={styles.textContainer}>
              <p>EVENTS | MAY 05 2021</p>
              <h1 className={styles.h1}>LEARN BASIC BING PREP</h1>
              <button className={styles.button}>REGISTER</button>
            </div>
            <div className={styles.picContainerThree}>
            <Image
              className={styles.chefPic}
              src="/images/sandwich.png"
              height={140}
              width={126}
            ></Image>
            </div>  
          </div>
        </div>

        <div className={styles.footer}>
          <div className={styles.bottomDeck}>
            <div className={styles.bottomCard}>
              <div className={styles.picContainer}>
                <Image
                  className={styles.logoPic}
                  src="/images/mingslogo.svg"
                  height={180}
                  width={126}
                ></Image>
              </div>  
              <div className={styles.textContainer}>
                <p>EVENTS | MAY 05 2021</p>
                <h1 className={styles.h1}>LEARN BASIC BING PREP</h1>
                <button className={styles.button}>REGISTER</button>
              </div>
            </div>
            <div className={styles.bottomCard}>
              <div className={styles.picContainer}>
                <Image
                  className={styles.logoPic}
                  src="/images/mingslogo.svg"
                  height={180}
                  width={126}
                ></Image>
              </div>  

              <div className={styles.textContainer}>
                  <p>EVENTS | MAY 05 2021</p>
                  <h1 className={styles.h1}>LEARN BASIC BING PREP</h1>
                  <button className={styles.button}>REGISTER</button>
              </div>
            </div>
            <div className={styles.bottomLast}>
            <div className={styles.picContainer}>
                <Image
                  className={styles.logoPic}
                  src="/images/mingslogo.svg"
                  height={180}
                  width={126}
                ></Image>
              </div>  

              <div className={styles.textContainer}>
                  <p>EVENTS | MAY 05 2021</p>
                  <h1 className={styles.h1}>LEARN BASIC BING PREP</h1>
                  <button className={styles.button}>REGISTER</button>
              </div>

            </div>
          </div>
          
        </div>

      </div>
    </>
  )
}
